from dataclasses import dataclass, fields, field
from typing import List

@dataclass(frozen=True)
class ColumnName:
    age: str = 'DriverAge'
    gender: str = 'GenderID'
    speed: str = 'Speed'
    number_of_fatalities: str = 'Number_Of_Fatalities'
    vehicle_year: str = 'VehicleYear'
    vehicle_make: str = 'VehicleMake'
    vehicle_model: str = 'VehicleModel'
    vehicle_disabled: str = 'VehicleDisabled'
    vehicle_towed : str = 'VehicleTowed'
    vehicle_plate_state: str = 'VehiclePlateState'
    vehicle_oversize: str = 'VehicleOversize'
    vehicle_cargo_spill: str = 'VehicleCargoSpill'
    vehicle_override : str = 'VehicleOverride'
    vehicle_underride: str = 'VehicleUnderride'
    vehicle_speed_before_crash: str = 'VehicleSpeedBeforeCrash'
    vehicle_speed_limit: str = 'VehicleSpeedLimit'
    vehicle_maximum_safe_speed: str = 'VehicleMaximumSafeSpeed'
    initial_impact: str = 'InitialImpact'
    direction_of_travel: str = 'DirectionOfTravel'
    first_event: str = 'FirstEvent'
    second_event: str = 'SecondEvent'
    third_event : str = 'ThirdEvent'
    fourth_event: str = 'FourthEvent'
    most_harmful_event: str = 'MostHarmfulEvent'
    city: str = 'City'
    state: str = 'State'
    license_state: str = 'LicenseState'
    defective_driver_ind: str = 'DefectiveDriverInd'
    year: str = 'Year_'
    crash_type_name: str = 'CrashTypeName'
    alcohol: str = 'Alcohol'
    cmv: str = 'CMV'
    pedestrian: str = 'Pedestrian'
    bicycle: str = 'Bicycle'
    motorcycle: str = 'Motorcycle'
    moped: str = 'Moped'
    train_related: str = 'TrainRelated'
    number_vehicles: str = 'NumberVehicles'
    work_zone: str = 'WorkZone'
    school_zone: str = 'SchoolZone'
    teen_driver_involved: str = 'TeenDriverInvolved'
    distraction_involved: str = 'DistractionInvolved'
    driver_texting_involved: str = 'DriverTextingInvolved'
    driver_using_cell_phone: str = 'DriverUsingCellPhone'
    unbelted_fatalities: str = 'UnbeltedFatalties'
    unbelted_serious_injury: str = 'UnbeltedSeriousInjury'
    alcohol_related_name: str = 'Alcohol_Related_Name'
    hour: str = 'Hour_'
    month_name: str = 'MonthName'
    day_name: str = 'DayName'
    three_hour_label: str = 'ThreeHourLabel'
    crash_date: str = 'CrashDate'
    county_name: str = 'County_Name'
    city_name: str = 'City_Name'
    town_name : str = 'Town_Name'
    crash_date_time: str = 'CrashDateTime'
    mile_marker: str = 'MileMarker'
    address_number: str = 'AddressNumber'
    secondary_location: str = 'SecondaryLocation'
    at_intersection: str = 'AtIntersection'
    national_highway_system: str = 'NationalHighwaySystem'
    route_signing: str = 'RouteSigning'
    functional_class_code: str = 'FunctionalClassCode'
    route_type_description: str = 'RouteTypeDescription'
    location_type_name: str = 'LocationTypeName'
    route_number: str = 'RouteNumber'
    route_name: str = 'RouteName'
    postal_city_name: str = 'PostalCityName'
    older_driver_inv: str = 'OlderDriverInv'
    older_fatals: str = 'OlderFatals'
    older_injured: str = 'OlderInjured'
    lrg_truck: str = 'LrgTruck'
    unrestrained_fatals: str = 'unrestrainedFatals'
    unrestained_injuries: str = 'UnrestrainedInjuries'
    ped_fatals: str = 'PedFatals'
    ped_injuries: str = 'PedInjuries'
    mc_fatals: str = 'MCFatals'
    mc_injuries: str = 'MCInjuries'
    bk_fatals: str = 'BKFatals'
    bk_injuries: str = 'BKInjuries'
    dd_fatals: str = 'DDFatals'
    dd_injuries: str = 'DDInjuries'
    unbelted_injury: str = 'UnbeltedInjury'
    number_of_injuries: str = 'Number_Of_Injuries'
    child_fatals_under_8: str = 'ChildFatalsUnder8'
    young_driver_aged_15_to_20_in_fatal_crashes: str = 'YoungDriverAged15to20InFatalCrashes'
    alcohol_impaired_driver_involved: str = 'Alcohol_Impaired_Driver_Involved'
    serious_injury_count: str = 'SeriousInjuryCount'
    crash_time: str = 'CrashTime'
    is_secondary_crash: str = 'IsSecondaryCrash'
    lane_clearance_date_time: str = 'LaneClearanceDateTime'
    scene_clearance_date_time: str = 'SceneClearanceDateTime'
    department: str = 'Department'
    vahso_region: str = 'VAHSORegion'















